"""영문판 KDP 등록에 필요한 모든 메타데이터를 생성한다.

생성 항목:
  - 책 설명 (HTML 형식, Amazon KDP English 최적화)
  - 7개 검색 키워드 (영문)
  - 저자 소개
  - 출판 준비 체크리스트

Usage:
    python generate_kdp_en_metadata.py
    python generate_kdp_en_metadata.py --force
"""
import argparse
import sys
import types

# ── config_en 을 'config' 로 주입 ─────────────────────────────────────────────
import config_en as _cfg_en

_config_shim = types.ModuleType("config")
_config_shim.__dict__.update(_cfg_en.__dict__)
sys.modules["config"] = _config_shim

from config_en import (  # noqa: E402
    AUTHOR_BIO_KDP, AUTHOR_NAME,
    BISAC_PRIMARY, BISAC_SECONDARY, BOOK_DIR, BOOK_SUBTITLE,
    BOOK_TITLE, CLAUDE_MODEL, EBOOK_PRICE_USD, LANGUAGE,
    OUTPUT_DIR, PRINT_PRICE_USD, PUBLISHER,
)
from llm import call_claude  # noqa: E402

# ── 영문 프롬프트 ──────────────────────────────────────────────────────────────
DESCRIPTION_PROMPT = """You are an Amazon book marketing specialist.
Write an Amazon KDP book description for the following technical book targeting English-speaking developers.

Book Details:
- Title: {title}
- Subtitle: {subtitle}
- Author: {author}
- Target audience: Python developers, AI/ML engineers, backend engineers deploying LLM-based agents
- Core value: Determine whether an AI agent is production-ready through code — not guesswork

Preface content (reference):
{intro_content}

Requirements:
1. HTML format (Amazon KDP supported tags: <h2>, <p>, <ul>, <li>, <b>, <br>)
2. Total 1500–2500 characters
3. Structure: Hook → Problem this book solves → Core content → What readers gain → CTA
4. Naturally embed search keywords: AI agent evaluation, LLM quality, Harness Engineering, production AI, agent testing
5. Tone: authoritative yet practical — speak to engineers, not managers

Return ONLY the HTML description text."""

KEYWORDS_PROMPT = """Select 7 Amazon KDP search keywords for this technical book.
Each keyword must be 7 words or fewer.

Book topic: {title} — {subtitle}
Target audience: Python developers building and deploying AI agents

Criteria:
- Terms developers actually search when looking for AI agent evaluation tools
- Mix of broad (ai agent testing) and specific (llm evaluation metrics python)
- Low competition, high intent keywords
- English only

Output format: one keyword per line, no numbering, no extra text."""


def load_intro() -> str:
    intro_path = BOOK_DIR / "00_서문.md"
    if intro_path.exists():
        return intro_path.read_text(encoding="utf-8")[:3000]
    return ""


def generate_description(intro: str) -> str:
    prompt = DESCRIPTION_PROMPT.format(
        title=BOOK_TITLE, subtitle=BOOK_SUBTITLE,
        author=AUTHOR_NAME, intro_content=intro,
    )
    return call_claude("", prompt, CLAUDE_MODEL, max_tokens=3000).strip()


def generate_keywords() -> list[str]:
    prompt = KEYWORDS_PROMPT.format(title=BOOK_TITLE, subtitle=BOOK_SUBTITLE)
    raw = call_claude("", prompt, CLAUDE_MODEL, max_tokens=300).strip()
    keywords = [k.strip() for k in raw.split("\n") if k.strip()]
    return keywords[:7]


CHECKLIST = """\
## KDP Registration Checklist

### Required Files
- [ ] EPUB file (generated by build_epub_en.py)
- [ ] Cover image (2560×1600px, JPG, 300 DPI, max 50 MB)
- [ ] Author photo (optional)

### KDP Registration Steps (kdp.amazon.com)
1. **Account Setup** → kdp.amazon.com → Enter tax info (W-8BEN for non-US authors)
2. **Add New Title** → Kindle eBook / Paperback
3. **Book Details**
   - Language: English
   - Book Title / Subtitle
   - Series (optional): Harness Engineering Series
   - Edition: 1
   - Author: {author}
   - Description: (paste generated HTML below)
   - Publishing Rights: ✅ I own the copyright
   - Keywords: (paste 7 keywords)
   - Categories: 2 selections
4. **Content Upload**
   - Manuscript: Upload EPUB file
   - Book Cover: Upload JPG
   - Preview: Use Kindle Previewer to verify layout
5. **Rights & Pricing**
   - Territory: All territories (worldwide)
   - Royalty: 70% (Kindle, $2.99–$9.99 range)
   - List Price: ${ebook_price} USD
   - KDP Select enrollment (optional — 90-day exclusive, Kindle Unlimited)
6. **Publish** → 72-hour review → Live on Amazon

### Pricing Strategy
| Format | Price | Royalty | Est. Per Sale |
|--------|-------|---------|---------------|
| Kindle eBook | ${ebook_price} | 70% | ${ebook_royalty:.2f} |
| Paperback (POD) | ${print_price} | 60%* | ${print_royalty:.2f} |

*After printing costs (~$5 for ~200 pages)

### English Market Optimization
- Primary market: amazon.com → Computers & Technology
- Secondary: amazon.co.uk, amazon.de, amazon.ca
- GitHub README badge linking to Amazon listing
- dev.to / Medium article cross-promotion
- PyPI agent-evaluator package description → Amazon link
""".format(
    author=AUTHOR_NAME,
    ebook_price=EBOOK_PRICE_USD,
    ebook_royalty=EBOOK_PRICE_USD * 0.70,
    print_price=PRINT_PRICE_USD,
    print_royalty=PRINT_PRICE_USD * 0.60 - 5.0,
)


def build_metadata_file(description: str, keywords: list[str], author_bio: str) -> str:
    lines = [
        f"# Amazon KDP Metadata — {BOOK_TITLE}",
        "",
        "---",
        "",
        "## Book Information",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Title | {BOOK_TITLE} |",
        f"| Subtitle | {BOOK_SUBTITLE} |",
        f"| Author | {AUTHOR_NAME} |",
        f"| Language | {LANGUAGE} |",
        f"| Publisher | {PUBLISHER} |",
        f"| BISAC Primary | {BISAC_PRIMARY} |",
        f"| BISAC Secondary | {BISAC_SECONDARY} |",
        f"| eBook Price | ${EBOOK_PRICE_USD} USD |",
        f"| Print Price | ${PRINT_PRICE_USD} USD |",
        "",
        "---",
        "",
        "## Book Description (HTML — paste directly into KDP)",
        "",
        "```html",
        description,
        "```",
        "",
        "---",
        "",
        "## Search Keywords (7)",
        "",
        "Enter each keyword in a separate KDP keyword field:",
        "",
    ]
    for i, kw in enumerate(keywords, 1):
        lines.append(f"{i}. {kw}")

    lines += [
        "",
        "---",
        "",
        "## Author Bio",
        "",
        author_bio,
        "",
        "---",
        "",
        CHECKLIST,
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="영문판 Amazon KDP 메타데이터 생성")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    out_dir = OUTPUT_DIR / "kdp"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "kdp_metadata_en.md"
    description_path = out_dir / "description_en.html"
    keywords_path = out_dir / "keywords_en.txt"

    if out_path.exists() and not args.force:
        print(f"[SKIP] {out_path} already exists. Use --force to overwrite.")
        return

    intro = load_intro()

    print("\n[KDP-EN] Generating book description...")
    description = generate_description(intro)

    print("[KDP-EN] Generating search keywords...")
    keywords = generate_keywords()

    print("[KDP-EN] Writing author bio...")
    author_bio = AUTHOR_BIO_KDP

    metadata = build_metadata_file(description, keywords, author_bio)
    out_path.write_text(metadata, encoding="utf-8")
    description_path.write_text(description, encoding="utf-8")
    keywords_path.write_text("\n".join(keywords), encoding="utf-8")

    print(f"\nDone:")
    print(f"  {out_path}       ← full metadata + checklist")
    print(f"  {description_path} ← HTML description (paste into KDP)")
    print(f"  {keywords_path}     ← 7 keywords")
    print(f"\nKeyword preview:")
    for i, kw in enumerate(keywords, 1):
        print(f"  {i}. {kw}")


if __name__ == "__main__":
    main()
