"""영문판 Amazon KDP 출판 준비 파이프라인 전체 실행.

Step 1: 한국어 Book/ → 영문 Book_EN/ 번역 (translate_to_en.py)
Step 2: 영문 KDP 메타데이터 생성 (generate_kdp_en_metadata.py)
Step 3: 영문 EPUB 빌드 (build_epub_en.py)

Usage:
    python run_kdp_en.py                    # 전체 파이프라인
    python run_kdp_en.py --translate-only   # 번역만
    python run_kdp_en.py --meta-only        # 메타데이터만
    python run_kdp_en.py --epub-only        # EPUB만
    python run_kdp_en.py --skip-translate   # 번역 생략 (이미 번역된 경우)
    python run_kdp_en.py --cover cover.jpg  # 표지 이미지 포함
    python run_kdp_en.py --force            # 기존 파일 덮어쓰기
    python run_kdp_en.py --check            # 의존성 확인
"""
import argparse
import subprocess
import sys
from pathlib import Path

PIPELINE_DIR = Path(__file__).parent


def run_script(script: str, extra_args: list[str]) -> bool:
    cmd = [sys.executable, str(PIPELINE_DIR / script)] + extra_args
    result = subprocess.run(cmd)
    return result.returncode == 0


def check_deps() -> bool:
    print("\n[Dependency Check]")
    ok = True

    # pandoc
    try:
        r = subprocess.run(["pandoc", "--version"], capture_output=True, text=True)
        print(f"  ✅ pandoc: {r.stdout.split(chr(10))[0]}")
    except FileNotFoundError:
        print("  ❌ pandoc: brew install pandoc  /  sudo apt install pandoc")
        ok = False

    # anthropic / claude CLI
    import shutil
    if shutil.which("claude"):
        print("  ✅ claude CLI: available (Claude Code auth)")
    else:
        import os
        from dotenv import load_dotenv
        load_dotenv(PIPELINE_DIR.parent.parent.parent / ".env")
        if os.getenv("ANTHROPIC_API_KEY", "").startswith("sk-ant-"):
            print("  ✅ ANTHROPIC_API_KEY: set")
        else:
            print("  ❌ claude CLI not found + ANTHROPIC_API_KEY not set")
            ok = False

    # Book_EN source
    book_en = PIPELINE_DIR.parent.parent.parent / "Book_EN"
    if book_en.exists():
        files = list(book_en.rglob("*.md"))
        print(f"  ✅ Book_EN/: {len(files)} markdown files")
    else:
        print("  ⬜ Book_EN/: not yet created (will be generated by translation step)")

    return ok


def print_final_checklist(output_dir: Path):
    kdp_dir = output_dir / "kdp"
    print(f"\n{'═' * 60}")
    print("  English KDP Upload Checklist")
    print(f"{'─' * 60}")
    files = {
        "EPUB file": list(kdp_dir.glob("*.epub")),
        "KDP metadata": [kdp_dir / "kdp_metadata_en.md"],
        "HTML description": [kdp_dir / "description_en.html"],
        "7 keywords": [kdp_dir / "keywords_en.txt"],
    }
    all_ok = True
    for label, paths in files.items():
        for p in paths:
            exists = p.exists()
            icon = "✅" if exists else "❌"
            size = f"  ({p.stat().st_size / 1024:.0f} KB)" if exists else " (missing)"
            print(f"  {icon} {label}: {p.name}{size}")
            if not exists:
                all_ok = False

    print(f"{'─' * 60}")
    if all_ok:
        print("  All files ready. Upload at kdp.amazon.com")
    else:
        print("  Some files missing — check errors above.")
    print(f"{'═' * 60}\n")

    print("  Next steps:")
    print("  1. Review output_en/kdp/kdp_metadata_en.md")
    print("  2. Create cover image (2560×1600px, JPG)")
    print("  3. python build_epub_en.py --cover cover.jpg  (add cover)")
    print("  4. kdp.amazon.com → Bookshelf → + Kindle eBook")


def main():
    parser = argparse.ArgumentParser(description="영문판 Amazon KDP 출판 파이프라인")
    parser.add_argument("--translate-only", action="store_true", help="번역만 실행")
    parser.add_argument("--meta-only", action="store_true", help="메타데이터만 생성")
    parser.add_argument("--epub-only", action="store_true", help="EPUB만 빌드")
    parser.add_argument("--skip-translate", action="store_true", help="번역 건너뜀")
    parser.add_argument("--cover", type=Path, help="표지 이미지 경로")
    parser.add_argument("--force", action="store_true", help="기존 파일 덮어쓰기")
    parser.add_argument("--check", action="store_true", help="의존성 확인만")
    args = parser.parse_args()

    if args.check:
        check_deps()
        return

    from config_en import OUTPUT_DIR

    print(f"\n{'█' * 60}")
    print("  AI Agent Harness Engineering — English KDP Pipeline")
    print(f"{'█' * 60}")

    force_arg = ["--force"] if args.force else []
    ran_anything = False

    # ── Step 1: Translation ───────────────────────────────────────────────────
    run_translate = not args.skip_translate and not args.meta_only and not args.epub_only
    if run_translate or args.translate_only:
        print("\n[Step 1] Korean → English Translation")
        ok = run_script("translate_to_en.py", ["--all"] + force_arg)
        if not ok:
            print("[FAIL] Translation failed.")
            sys.exit(1)
        ran_anything = True

    if args.translate_only:
        print("\nTranslation complete. Run without --translate-only for full pipeline.")
        return

    # ── Step 2: KDP Metadata ──────────────────────────────────────────────────
    run_meta = not args.epub_only
    if run_meta:
        print("\n[Step 2] English KDP Metadata")
        ok = run_script("generate_kdp_en_metadata.py", force_arg)
        if not ok:
            print("[FAIL] Metadata generation failed.")
            sys.exit(1)
        ran_anything = True

    if args.meta_only:
        return

    # ── Step 3: EPUB Build ────────────────────────────────────────────────────
    print("\n[Step 3] English EPUB Build")
    epub_args = force_arg.copy()
    if args.cover:
        epub_args += ["--cover", str(args.cover)]
    ok = run_script("build_epub_en.py", epub_args)
    if not ok:
        print("[FAIL] EPUB build failed.")
        sys.exit(1)
    ran_anything = True

    if ran_anything:
        print_final_checklist(OUTPUT_DIR)


if __name__ == "__main__":
    main()
